// =================================================================================
//                            CHEMISTRY CLASS 12
// =================================================================================
export const chemistryXII = [
  {
    id: 1,
    title: 'The Solid State',
    summary: 'An exploration of the ordered arrangement of particles in solids and how this structure dictates their physical properties.',
    detailedExplanation: "This chapter delves into the arrangement of constituent particles in solids, leading to their distinct properties. We differentiate between amorphous solids, which lack long-range order, and crystalline solids, which have a well-defined, repeating three-dimensional structure. The concept of the crystal lattice and the unit cell, its smallest repeating unit, is fundamental. We explore how different packing arrangements (like simple cubic, BCC, FCC) affect density and packing efficiency, and how imperfections or 'defects' in these structures give rise to unique electrical and magnetic properties.",
    keyTopics: ['General Characteristics of Solid State', 'Amorphous and Crystalline Solids', 'Crystal Lattices and Unit Cells', 'Packing Efficiency', 'Imperfections in Solids', 'Electrical and Magnetic Properties'],
    realWorldExample: "Diamond's hardness comes from its 3D network of carbon atoms in a crystal lattice, used in cutting tools.",
    keyEquation: 'Density = (Z * M) / (a^3 * N_A)',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/?codid=1100025',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
        { title: 'Khan Academy: Introduction to the Solid State', url: 'https://www.khanacademy.org/science/chemistry/states-of-matter-and-intermolecular-forces/solids/v/introduction-to-solids' },
        { title: 'Chemistry LibreTexts: Crystalline Solids', url: 'https://chem.libretexts.org/Bookshelves/General_Chemistry/Map%3A_Chemistry_-_The_Central_Science_(Brown_et_al.)/11%3A_Liquids_and_Intermolecular_Forces/11.8%3A_Crystalline_Solids' },
    ],
    quiz: [
      { question: 'What is the basic unit of a crystal lattice?', options: ['Molecule', 'Unit Cell', 'Atom', 'Ion'], correct: 'Unit Cell' },
      { question: 'Which solids lack long-range order?', options: ['Crystalline', 'Amorphous', 'Metallic', 'Ionic'], correct: 'Amorphous' },
    ],
  },
  {
    id: 2,
    title: 'Solutions',
    summary: 'A study of homogeneous mixtures, their concentrations, and properties that depend on the quantity of solute particles.',
    detailedExplanation: "A solution is a homogeneous mixture of two or more substances. This chapter explores how to express the concentration of solutions in various units like molarity, molality, and mole fraction. We examine the factors affecting solubility, and the behavior of solutions based on Raoult's Law, distinguishing between ideal and non-ideal solutions. A key focus is on colligative properties—properties that depend only on the number of solute particles, not their identity. These include vapor pressure lowering, boiling point elevation, freezing point depression, and osmotic pressure, which have important applications in determining molar masses.",
    keyTopics: ['Types of Solutions', 'Expressing Concentration', 'Solubility', 'Vapour Pressure', 'Ideal and Non-ideal Solutions', 'Colligative Properties', 'Abnormal Molar Masses'],
    realWorldExample: 'Antifreeze in car radiators works by lowering the freezing point of water, a colligative property.',
    keyEquation: 'π = iMRT (Osmotic Pressure)',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
        { title: 'Crash Course Chemistry: Solutions', url: 'https://www.youtube.com/watch?v=9h2f1Bjr0p4' },
        { title: 'PhET Simulation: Molarity', url: 'https://phet.colorado.edu/en/simulations/molarity' },
    ],
    quiz: [
      { question: 'Which is a colligative property?', options: ['Density', 'Boiling point elevation', 'Reactivity', 'Color'], correct: 'Boiling point elevation' },
      { question: 'What is the unit of molarity?', options: ['mol/L', 'g/L', 'mol/kg', 'L/mol'], correct: 'mol/L' },
    ],
  },
  {
    id: 3,
    title: 'Electrochemistry',
    summary: 'Investigating the relationship between chemical reactions and electrical energy in galvanic and electrolytic cells.',
    detailedExplanation: "Electrochemistry bridges the gap between chemical energy and electrical energy. It covers two main types of cells: galvanic (or voltaic) cells, which generate electricity from spontaneous chemical reactions (like in batteries), and electrolytic cells, which use electricity to drive non-spontaneous reactions (like in electrolysis). The Nernst equation is introduced to calculate cell potential under non-standard conditions. The chapter also explores the conductivity of electrolytic solutions, the principles behind different types of batteries and fuel cells, and the electrochemical process of corrosion (rusting).",
    keyTopics: ['Electrochemical Cells', 'Galvanic Cells', 'Nernst Equation', 'Conductance of Electrolytic Solutions', 'Electrolysis', 'Batteries', 'Fuel Cells', 'Corrosion'],
    realWorldExample: 'Car batteries use lead-acid electrochemical reactions to provide electrical energy.',
    keyEquation: 'E = E° - (RT/nF)ln(Q)',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
        { title: 'Khan Academy: Electrochemistry', url: 'https://www.khanacademy.org/science/chemistry/oxidation-reduction' },
        { title: 'The Organic Chemistry Tutor: Electrochemistry Review', url: 'https://www.youtube.com/watch?v=J8_SfcS-S3M' },
    ],
    quiz: [
      { question: 'Which cell converts chemical energy to electrical?', options: ['Electrolytic', 'Galvanic', 'Fuel', 'Solar'], correct: 'Galvanic' },
      { question: 'What causes corrosion?', options: ['Oxidation', 'Reduction', 'Neutralization', 'Combustion'], correct: 'Oxidation' },
    ],
  },
  {
    id: 4,
    title: 'Chemical Kinetics',
    summary: 'Explores the speed of chemical reactions, the factors influencing them, and the step-by-step mechanisms they follow.',
    detailedExplanation: "This chapter focuses on the rate of chemical reactions and the factors that influence it, such as concentration, temperature, pressure, and catalysts. We study rate laws and integrated rate equations for zero, first, and second-order reactions, which allow us to predict reactant concentrations over time. The concept of half-life is introduced as a measure of reaction speed. The Arrhenius equation and collision theory provide a molecular-level understanding of how temperature affects reaction rates by relating it to activation energy—the minimum energy required for a reaction to occur.",
    keyTopics: ['Rate of a Chemical Reaction', 'Factors Influencing Rate', 'Integrated Rate Equations', 'Temperature Dependence', 'Collision Theory'],
    realWorldExample: 'Catalysts in car exhaust systems speed up the conversion of harmful gases to less toxic substances.',
    keyEquation: 'k = A * e^(-Ea/RT)',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Chemical Kinetics', url: 'https://www.khanacademy.org/science/chemistry/chem-kinetics' },
      { title: 'PhET Simulation: Reactions & Rates', url: 'https://phet.colorado.edu/en/simulations/reactions-and-rates' },
    ],
    quiz: [
      { question: 'Which factor increases reaction rate?', options: ['Low temperature', 'Catalyst', 'Low concentration', 'Large particles'], correct: 'Catalyst' },
      { question: 'What does Ea represent in the Arrhenius equation?', options: ['Activation energy', 'Equilibrium energy', 'Enthalpy', 'Entropy'], correct: 'Activation energy' },
    ],
  },
  {
    id: 5,
    title: 'Surface Chemistry',
    summary: 'A study of chemical phenomena that occur at the interfaces between different phases, such as adsorption and catalysis.',
    detailedExplanation: "Surface chemistry deals with the processes that occur at the boundary, or surface, between two different phases. Key topics include adsorption, where molecules adhere to the surface of a solid or liquid, and catalysis, where a substance (catalyst) increases the rate of a chemical reaction without being consumed. The chapter also explores colloids—mixtures where one substance of microscopically dispersed insoluble particles is suspended throughout another substance—and emulsions, which are a specific type of colloid involving two immiscible liquids.",
    keyTopics: ['Adsorption', 'Catalysis', 'Colloids', 'Classification of Colloids', 'Emulsions', 'Colloids Around Us'],
    realWorldExample: 'Activated charcoal adsorbs impurities in water purification systems.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'BYJU\'S: Surface Chemistry', url: 'https://byjus.com/chemistry/surface-chemistry/' },
      { title: 'Chem LibreTexts: Colloids', url: 'https://chem.libretexts.org/Bookshelves/General_Chemistry/Map%3A_Chemistry_-_The_Central_Science_(Brown_et_al.)/13%3A_Properties_of_Mixtures%3A_Solutions_and_Colloids/13.6%3A_Colloids' },
    ],
    quiz: [
      { question: 'What is adsorption?', options: ['Desorption', 'Surface accumulation', 'Dissolution', 'Evaporation'], correct: 'Surface accumulation' },
      { question: 'What is the Tyndall effect?', options: ['Color change', 'Light scattering', 'Heat absorption', 'Gas emission'], correct: 'Light scattering' },
    ],
  },
  {
    id: 6,
    title: 'General Principles and Processes of Isolation of Elements',
    summary: 'An overview of metallurgy, covering the principles and processes used to extract pure metals from their natural ores.',
    detailedExplanation: "This chapter covers the science of metallurgy—the process of extracting metals from their ores found in the Earth's crust. It outlines the major steps involved: concentration of the ore to remove impurities, extraction of the crude metal from the concentrated ore (often through reduction processes like smelting), and finally, the refining of the crude metal to achieve high purity. Thermodynamic and electrochemical principles are applied to understand the feasibility and efficiency of these extraction and refining methods, such as electrolysis and zone refining.",
    keyTopics: ['Occurrence of Metals', 'Concentration of Ores', 'Extraction of Crude Metal', 'Thermodynamic Principles of Metallurgy', 'Electrochemical Principles', 'Refining'],
    realWorldExample: 'Aluminum is extracted from bauxite ore and used in aircraft construction.',
    keyEquation: 'ΔG = ΔH - TΔS',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Toppr: General Principles and Processes of Isolation of Elements', url: 'https://www.toppr.com/guides/chemistry/general-principles-and-processes-of-isolation-of-elements/' },
      { title: 'Khan Academy: Introduction to Metallurgy', url: 'https://www.khanacademy.org/science/chemistry/chemistry-of-elements/metallurgy/v/introduction-to-metallurgy' },
    ],
    quiz: [
      { question: 'Which ore is aluminum extracted from?', options: ['Hematite', 'Bauxite', 'Malachite', 'Cinnabar'], correct: 'Bauxite' },
      { question: 'What is the main reducing agent in metallurgy?', options: ['Oxygen', 'Carbon', 'Nitrogen', 'Hydrogen'], correct: 'Carbon' },
    ],
  },
  {
    id: 7,
    title: 'The p-Block Elements',
    summary: 'A detailed survey of elements in Groups 13 to 18, focusing on their trends, properties, and important compounds.',
    detailedExplanation: "The p-block of the periodic table contains a diverse range of elements, including metals, metalloids, and non-metals. This chapter provides a systematic study of these elements, group by group (from Group 13 to 18). It explores the periodic trends in their electronic configuration, atomic size, ionization enthalpy, and electronegativity. Special attention is given to the unique chemistry of key compounds like ammonia, nitric acid, ozone, sulfuric acid, the halogens, and the inert gases, highlighting their industrial and environmental importance.",
    keyTopics: ['Group 15 Elements (Nitrogen family)', 'Group 16 Elements (Oxygen family)', 'Group 17 Elements (Halogens)', 'Group 18 Elements (Noble Gases)', 'Important Compounds and their Properties'],
    realWorldExample: 'Sulphuric acid is widely used in fertilizer production and is known as the "king of chemicals".',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'JagranJosh: The p-Block Elements', url: 'https://www.jagranjosh.com/articles/cbse-class-12-chemistry-p-block-elements-notes-1505389028-1' },
      { title: 'Chem LibreTexts: The Main Group (p-Block) Elements', url: 'https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry/Book%3A_Inorganic_Chemistry_(Saito)/4%3A_Chemistry_of_Main_Group_Elements' },
    ],
    quiz: [
      { question: 'Which element is in Group 15?', options: ['Oxygen', 'Nitrogen', 'Carbon', 'Fluorine'], correct: 'Nitrogen' },
      { question: 'Which noble gas is most reactive?', options: ['Helium', 'Neon', 'Argon', 'Xenon'], correct: 'Xenon' },
    ],
  },
  {
    id: 8,
    title: 'The d-and f-Block Elements',
    summary: 'An examination of the transition metals (d-block) and inner transition metals (f-block), known for their unique properties like variable oxidation states and colored ions.',
    detailedExplanation: "This chapter focuses on the transition elements (d-block) and inner transition elements (f-block: lanthanoids and actinoids). It discusses their position in the periodic table and their characteristic properties, which include forming colored ions, exhibiting variable oxidation states, acting as catalysts, and forming complex compounds. The chapter explains these properties based on their partially filled d and f orbitals. It also covers the phenomenon of lanthanoid contraction and the chemistry of important compounds like potassium permanganate and potassium dichromate.",
    keyTopics: ['Position in the Periodic Table', 'Electronic Configurations', 'Properties of Transition Elements', 'Important Compounds', 'The Lanthanoids', 'The Actinoids'],
    realWorldExample: 'Iron is a key component of steel and is essential for construction and manufacturing.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'BYJU\'S: d and f Block Elements', url: 'https://byjus.com/chemistry/d-and-f-block-elements/' },
      { title: 'Vedantu: Transition Metals (d-block)', url: 'https://www.vedantu.com/chemistry/transition-elements' },
    ],
    quiz: [
      { question: 'What is a characteristic property of transition metals?', options: ['Fixed oxidation state', 'Variable oxidation states', 'Non-metallic', 'Gaseous state'], correct: 'Variable oxidation states' },
      { question: 'Which block contains the lanthanoids?', options: ['s-block', 'p-block', 'd-block', 'f-block'], correct: 'f-block' },
    ],
  },
  {
    id: 9,
    title: 'Coordination Compounds',
    summary: 'A study of complex compounds formed by a central metal atom bonded to surrounding molecules or ions, known as ligands.',
    detailedExplanation: "Coordination compounds consist of a central metal atom or ion bonded to a number of molecules or anions, called ligands. This chapter introduces Werner's theory as the foundation for their structure. It covers the nomenclature, isomerism (structural and stereoisomerism), and bonding in these compounds, explaining theories like Valence Bond Theory and Crystal Field Theory. These theories help explain the color and magnetic properties of coordination complexes. The chapter concludes by highlighting their importance in analytical chemistry, metallurgy, and biological systems like hemoglobin and chlorophyll.",
    keyTopics: ["Werner's Theory", 'Definitions and Nomenclature', 'Isomerism', 'Bonding in Coordination Compounds', 'Stability and Applications'],
    realWorldExample: "Hemoglobin in blood is a coordination compound of iron that transports oxygen.",
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Coordination Compounds', url: 'https://www.khanacademy.org/science/chemistry/transition-metals/coordination-compounds-and-complex-ions/v/introduction-to-coordination-compounds' },
      { title: 'Chem LibreTexts: Coordination Chemistry', url: 'https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry/Supplemental_Modules_and_Websites_(Inorganic_Chemistry)/Coordination_Chemistry' },
    ],
    quiz: [
      { question: 'What is a ligand?', options: ['Central atom', 'Ion', 'Molecule bonded to metal', 'Salt'], correct: 'Molecule bonded to metal' },
      { question: 'Which bonding theory explains the color of coordination compounds?', options: ['Valence Bond Theory', 'Crystal Field Theory', 'Molecular Orbital Theory', 'Lewis Theory'], correct: 'Crystal Field Theory' },
    ],
  },
  {
    id: 10,
    title: 'Haloalkanes and Haloarenes',
    summary: 'An introduction to organic compounds containing halogen atoms, focusing on their preparation, properties, and reaction mechanisms.',
    detailedExplanation: "This chapter introduces the class of organic compounds formed by replacing hydrogen atoms in hydrocarbons with halogen atoms. It covers their classification, nomenclature, and the nature of the carbon-halogen (C-X) bond. A significant focus is placed on their chemical reactions, particularly nucleophilic substitution (SN1 and SN2 mechanisms) and elimination reactions for haloalkanes, and electrophilic substitution for haloarenes. The chapter also discusses the properties and environmental impact of important polyhalogen compounds like chloroform, freons, and DDT.",
    keyTopics: ['Classification and Nomenclature', 'Nature of C-X Bond', 'Methods of Preparation', 'Physical Properties', 'Chemical Reactions', 'Polyhalogen Compounds'],
    realWorldExample: 'Teflon, a non-stick coating, is a polymer of tetrafluoroethylene, a haloalkane derivative.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'The Organic Chemistry Tutor: Haloalkanes and Haloarenes', url: 'https://www.youtube.com/watch?v=wM7pdeI1JqE' },
      { title: 'BYJU\'S: SN1 and SN2 Reaction Mechanism', url: 'https://byjus.com/chemistry/sn1-sn2-reaction-mechanism/' },
    ],
    quiz: [
      { question: 'Which reaction is characteristic of haloalkanes?', options: ['Nucleophilic substitution', 'Electrophilic substitution', 'Addition', 'Elimination'], correct: 'Nucleophilic substitution' },
      { question: 'What is the common name for trichloromethane?', options: ['Freon', 'Chloroform', 'Carbon tetrachloride', 'DDT'], correct: 'Chloroform' },
    ],
  },
  {
    id: 11,
    title: 'Alcohols, Phenols and Ethers',
    summary: 'An exploration of organic compounds containing hydroxyl (-OH) or ether (R-O-R\') functional groups, including their properties and reactions.',
    detailedExplanation: "This unit focuses on three important classes of organic compounds. Alcohols and phenols contain one or more hydroxyl (-OH) groups, while ethers are characterized by an oxygen atom connected to two alkyl or aryl groups. The chapter covers their classification, nomenclature, and methods of preparation. It compares the acidity of alcohols and phenols, and details their characteristic reactions, such as dehydration, oxidation, and Williamson synthesis for ethers. The uses of commercially important alcohols like methanol and ethanol are also discussed.",
    keyTopics: ['Classification and Nomenclature', 'Structures of Functional Groups', 'Preparation of Alcohols, Phenols, and Ethers', 'Physical and Chemical Properties', 'Commercially Important Alcohols'],
    realWorldExample: 'Ethanol is used as a beverage, a fuel, and a solvent.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Alcohols, Ethers, and Phenols', url: 'https://www.khanacademy.org/science/organic-chemistry/alcohols-ethers-epoxides-sulfides' },
      { title: 'Chem LibreTexts: Williamson Ether Synthesis', url: 'https://chem.libretexts.org/Bookshelves/Organic_Chemistry/Organic_Chemistry_(Morsch_et_al.)/18%3A_Ethers_and_Epoxides%3B_Thiols_and_Sulfides/18.03%3A_The_Williamson_Ether_Synthesis' },
    ],
    quiz: [
      { question: "Which test distinguishes between primary, secondary, and tertiary alcohols?", options: ["Fehling's test", "Tollens' test", "Lucas test", 'Iodoform test'], correct: 'Lucas test' },
      { question: "What is the main reaction to prepare ethers?", options: ["Williamson synthesis", "Grignard reaction", "Friedel-Crafts reaction", "Clemmensen reduction"], correct: 'Williamson synthesis' },
    ],
  },
  {
    id: 12,
    title: 'Aldehydes, Ketones and Carboxylic Acids',
    summary: 'A detailed study of organic compounds containing the carbonyl (C=O) and carboxyl (-COOH) functional groups.',
    detailedExplanation: "This chapter is central to organic chemistry as it deals with compounds containing the carbonyl group. It discusses the nomenclature, preparation, and reactions of aldehydes and ketones. Key reactions include nucleophilic addition, reduction (to alcohols), oxidation, and condensation reactions like the Aldol and Cannizzaro reactions. The second part of the chapter focuses on carboxylic acids, covering their acidic nature, methods of preparation, and reactions that lead to the formation of important derivatives like esters, amides, and acid anhydrides.",
    keyTopics: ['Structure of Carbonyl Group', 'Preparation of Aldehydes and Ketones', 'Nucleophilic Addition Reactions', 'Structure of Carboxyl Group', 'Preparation of Carboxylic Acids', 'Acidity and Reactions'],
    realWorldExample: 'Acetic acid is the main component of vinegar, and acetone is a common solvent in nail polish remover.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Crash Course Chemistry: Carbonyl Compounds', url: 'https://www.youtube.com/watch?v=J_M29i02t-U' },
      { title: 'Chem LibreTexts: Aldehydes and Ketones', url: 'https://chem.libretexts.org/Bookshelves/Organic_Chemistry/Organic_Chemistry_(Morsch_et_al.)/19%3A_Aldehydes_and_Ketones' },
    ],
    quiz: [
      { question: "Which test is used to distinguish between aldehydes and ketones?", options: ["Lucas test", "Tollens' test", "Iodoform test", "Fehling's test"], correct: "Tollens' test" },
      { question: 'Which reaction converts a carboxylic acid to an ester?', options: ['Saponification', 'Esterification', 'Hydrolysis', 'Oxidation'], correct: 'Esterification' },
    ],
  },
  {
    id: 13,
    title: 'Amines',
    summary: 'A study of organic compounds derived from ammonia, focusing on their basic nature, preparation, and role in synthesis.',
    detailedExplanation: "Amines are organic derivatives of ammonia, classified as primary, secondary, or tertiary based on the number of alkyl or aryl groups attached to the nitrogen atom. This chapter explores their structure, nomenclature, and methods of preparation, such as the reduction of nitro compounds and the Hofmann bromamide degradation. A key feature of amines is their basicity, which is compared across different types of amines. The chapter also covers their characteristic reactions and the chemistry of diazonium salts, which are important synthetic intermediates for preparing a variety of aromatic compounds.",
    keyTopics: ['Structure and Classification', 'Nomenclature', 'Preparation of Amines', 'Physical and Chemical Properties', 'Basicity of Amines', 'Diazonium Salts'],
    realWorldExample: 'Many medicines, such as antihistamines and painkillers, are based on amine structures.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'The Organic Chemistry Tutor: Amines - Basic Introduction', url: 'https://www.youtube.com/watch?v=5Y6yefQ_IuE' },
      { title: 'Chem LibreTexts: Basicity of Amines', url: 'https://chem.libretexts.org/Bookshelves/Organic_Chemistry/Organic_Chemistry_(Morsch_et_al.)/24%3A_Amines/24.04%3A_Basicity_of_Amines' },
    ],
    quiz: [
      { question: 'What is the nature of amines?', options: ['Acidic', 'Basic', 'Neutral', 'Amphoteric'], correct: 'Basic' },
      { question: "Which test is used to identify primary amines?", options: ['Carbylamine test', 'Lucas test', "Tollens' test", "Fehling's test"], correct: 'Carbylamine test' },
    ],
  },
  {
    id: 14,
    title: 'Biomolecules',
    summary: 'An introduction to the chemistry of life, exploring the structure and function of carbohydrates, proteins, nucleic acids, and vitamins.',
    detailedExplanation: "This chapter bridges chemistry and biology by studying the molecules that make up living organisms. It covers carbohydrates (from monosaccharides like glucose to polysaccharides like starch and cellulose), proteins (polymers of amino acids linked by peptide bonds, with complex 3D structures), and nucleic acids (DNA and RNA, the molecules of heredity). The roles of enzymes as biological catalysts, vitamins as essential micronutrients, and hormones as chemical messengers are also discussed, providing a molecular basis for biological processes.",
    keyTopics: ['Carbohydrates', 'Proteins', 'Amino Acids and Peptide Bonds', 'Enzymes', 'Vitamins', 'Nucleic Acids (DNA and RNA)'],
    realWorldExample: 'DNA carries the genetic instructions for the development and functioning of all known living organisms.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Amoeba Sisters: Biomolecules', url: 'https://www.youtube.com/watch?v=yo_24_qT5P8' },
      { title: 'Khan Academy: Biomolecules', url: 'https://www.khanacademy.org/science/biology/macromolecules' },
    ],
    quiz: [
      { question: 'What is the monomer of proteins?', options: ['Glucose', 'Amino acid', 'Nucleotide', 'Fatty acid'], correct: 'Amino acid' },
      { question: 'Which nucleic acid contains uracil?', options: ['DNA', 'RNA', 'Both', 'Neither'], correct: 'RNA' },
    ],
  },
  {
    id: 15,
    title: 'Polymers',
    summary: 'A study of macromolecules, focusing on their classification, types of polymerization, and the properties of commercially important synthetic and natural polymers.',
    detailedExplanation: "Polymers are large molecules (macromolecules) composed of many repeating subunits called monomers. This chapter classifies polymers based on their source, structure, and mode of polymerization (addition and condensation). It discusses the synthesis and properties of commercially important polymers like polythene, PVC, nylon, and Bakelite. The concept of rubber vulcanization is explained, and the chapter also touches upon biodegradable polymers as a solution to environmental issues caused by plastic waste.",
    keyTopics: ['Classification of Polymers', 'Types of Polymerisation Reactions', 'Molecular Mass', 'Biodegradable Polymers', 'Commercially Important Polymers'],
    realWorldExample: 'Plastic bottles are made of a polymer called polyethylene terephthalate (PET).',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Crash Course Chemistry: Polymers', url: 'https://www.youtube.com/watch?v=rHxxLYzJ8wY' },
      { title: 'Chem LibreTexts: Introduction to Polymers', url: 'https://chem.libretexts.org/Bookshelves/Organic_Chemistry/Organic_Chemistry_(Morsch_et_al.)/29%3A_Polymers/29.01%3A_Introduction_to_Polymers' },
    ],
    quiz: [
      { question: 'Which is a natural polymer?', options: ['Nylon', 'PVC', 'Cellulose', 'Polyester'], correct: 'Cellulose' },
      { question: 'What is the process of heating rubber with sulfur called?', options: ['Vulcanization', 'Polymerization', 'Galvanization', 'Hydrogenation'], correct: 'Vulcanization' },
    ],
  },
  {
    id: 16,
    title: 'Chemistry in Everyday Life',
    summary: 'An exploration of the vital role chemistry plays in medicine, food, and cleaning agents that we use daily.',
    detailedExplanation: "This chapter highlights the practical applications of chemistry in our daily lives. It explores the chemistry of medicines, classifying drugs based on their therapeutic action, such as analgesics, antibiotics, antiseptics, and antacids. It also delves into the chemistry of food, discussing artificial sweeteners, preservatives, and antioxidants. Finally, the chapter explains the cleansing action of soaps and detergents, differentiating between them and explaining the formation of micelles.",
    keyTopics: ['Drugs and their Classification', 'Drug-Target Interaction', 'Therapeutic Action of Drugs', 'Chemistry in Food', 'Cleansing Agents (Soaps and Detergents)'],
    realWorldExample: 'Soaps and detergents are chemical compounds used for cleaning.',
    keyEquation: '',
    icon: 'flask',
    visualizationLinks: [
      'https://molview.org/',
      'https://www.chemtube3d.com/',
      'https://vchem3d.univ-tlse3.fr/index.html',
    ],
    resourceLinks: [
      { title: 'Toppr: Chemistry in Everyday Life', url: 'https://www.toppr.com/guides/chemistry/chemistry-in-everyday-life/' },
      { title: 'BYJU\'S: Cleansing Action of Soap', url: 'https://byjus.com/chemistry/cleansing-action-of-soap/' },
    ],
    quiz: [
      { question: 'Which is an example of an antiseptic?', options: ['Soap', 'Dettol', 'Aspirin', 'Penicillin'], correct: 'Dettol' },
      { question: 'Which type of drug reduces pain?', options: ['Antipyretic', 'Analgesic', 'Antiseptic', 'Antibiotic'], correct: 'Analgesic' },
    ],
  },
];

// =================================================================================
//                            BIOLOGY CLASS 12
// =================================================================================
export const biologyXII = [
  {
    id: 1,
    title: 'Sexual Reproduction in Flowering Plants',
    summary: 'An in-depth look at the structures and events leading to the creation of seeds and fruits in angiosperms.',
    detailedExplanation: "This unit covers the intricate process of sexual reproduction in flowering plants (angiosperms). It begins with the structure of a flower and its reproductive parts: the stamen (male) and pistil (female). We explore the development of male and female gametophytes (pollen grain and embryo sac), the process of pollination, and the unique phenomenon of double fertilization, where one male gamete fertilizes the egg to form the zygote, and the other fuses with the central cell to form the nutritive endosperm. The chapter concludes with post-fertilization events, including the development of the embryo, endosperm, seed, and fruit, as well as special cases like apomixis and polyembryony.",
    keyTopics: ['Flower Structure', 'Pre-fertilisation Events', 'Double Fertilisation', 'Post-fertilisation Events', 'Apomixis and Polyembryony'],
    realWorldExample: 'The development of fruits like apples and oranges is a direct result of sexual reproduction in their flowers.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
        { title: 'Khan Academy: Flowering Plant Reproduction', url: 'https://www.khanacademy.org/science/biology/flower-and-plant-reproduction' },
        { title: 'Amoeba Sisters: Plant Reproduction in Angiosperms', url: 'https://www.youtube.com/watch?v=2-n-1i5z50o' },
    ],
    quiz: [
      { question: 'What is the male reproductive part of a flower called?', options: ['Pistil', 'Stamen', 'Petal', 'Sepal'], correct: 'Stamen' },
      { question: 'What does the ovary of a flower develop into?', options: ['Seed', 'Fruit', 'Stem', 'Leaf'], correct: 'Fruit' },
    ],
  },
  {
    id: 2,
    title: 'Human Reproduction',
    summary: 'A detailed study of the human reproductive systems, gamete formation, fertilization, and embryonic development.',
    detailedExplanation: "This chapter provides a comprehensive overview of the human reproductive system. It details the anatomy and physiology of the male and female reproductive systems, including their primary and accessory organs. The process of gametogenesis—spermatogenesis in males and oogenesis in females—is explained in detail. The chapter then covers the menstrual cycle and its hormonal regulation, the events of fertilization and implantation, followed by pregnancy and embryonic development (gestation). It concludes with the processes of parturition (childbirth) and lactation (milk production), highlighting the complex hormonal control that governs these life-sustaining events.",
    keyTopics: ['Male & Female Reproductive Systems', 'Gametogenesis', 'Menstrual Cycle', 'Fertilisation & Implantation', 'Pregnancy & Embryonic Development', 'Parturition & Lactation'],
    realWorldExample: 'The understanding of the menstrual cycle is crucial for family planning and reproductive health.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
        { title: 'Khan Academy: Human Reproduction', url: 'https://www.khanacademy.org/science/health-and-medicine/human-anatomy-and-physiology/human-reproduction' },
        { title: 'Visible Body: Human Reproductive System', url: 'https://www.visiblebody.com/learn/reproductive' },
    ],
    quiz: [
      { question: 'Where does fertilization typically occur in humans?', options: ['Ovary', 'Uterus', 'Fallopian tube', 'Vagina'], correct: 'Fallopian tube' },
      { question: 'Which hormone is primarily responsible for the development of male secondary sexual characteristics?', options: ['Estrogen', 'Progesterone', 'Testosterone', 'LH'], correct: 'Testosterone' },
    ],
  },
  {
    id: 3,
    title: 'Reproductive Health',
    summary: 'An examination of societal issues related to reproductive health, including population control, STIs, and infertility.',
    detailedExplanation: "This unit addresses the concept of reproductive health as a state of complete physical, mental, and social well-being in all matters relating to the reproductive system. It examines societal problems like population explosion and discusses various methods of birth control, including natural, barrier, hormonal, and surgical methods. The chapter also covers sensitive and important topics such as Medical Termination of Pregnancy (MTP), the causes and prevention of Sexually Transmitted Infections (STIs), and the challenges of infertility. It introduces Assisted Reproductive Technologies (ART) like IVF and ZIFT as solutions for infertile couples.",
    keyTopics: ['Reproductive Health Issues', 'Population Control & Contraception', 'Medical Termination of Pregnancy', 'Sexually Transmitted Infections (STIs)', 'Infertility & ART'],
    realWorldExample: 'The use of contraceptives has played a significant role in controlling population growth and preventing STIs.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'World Health Organization (WHO): Reproductive Health', url: 'https://www.who.int/health-topics/sexual-and-reproductive-health' },
      { title: 'Crash Course Biology: Reproductive Health', url: 'https://www.youtube.com/watch?v=g_i1_S4g6-g' },
    ],
    quiz: [
      { question: 'Which of the following is a barrier method of contraception?', options: ['Condom', 'Oral pill', 'IUD', 'Vasectomy'], correct: 'Condom' },
      { question: "What does 'IVF' stand for?", options: ['Intra-vaginal Fertilization', 'In Vitro Fertilization', 'Intra-uterine Fertilization', 'In Vivo Fertilization'], correct: 'In Vitro Fertilization' },
    ],
  },
  {
    id: 4,
    title: 'Principles of Inheritance and Variation',
    summary: 'A journey into genetics, exploring Mendel\'s foundational laws, patterns of inheritance, and the origins of genetic disorders.',
    detailedExplanation: "This chapter lays the groundwork for classical genetics. It begins with Mendel's experiments on pea plants, leading to the formulation of his three fundamental laws: the Law of Dominance, the Law of Segregation, and the Law of Independent Assortment. The concepts are extended to more complex patterns like incomplete dominance, co-dominance, and multiple alleles. The chapter also covers sex determination mechanisms, the concept of genetic mutation as a source of variation, and provides an overview of common Mendelian and chromosomal genetic disorders in humans, such as hemophilia and Down's syndrome.",
    keyTopics: ["Mendel's Laws of Inheritance", 'Inheritance of One and Two Genes', 'Sex Determination', 'Mutation', 'Genetic Disorders'],
    realWorldExample: 'Understanding genetic disorders like sickle-cell anemia helps in diagnosis and genetic counseling.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Amoeba Sisters: Mendelian Genetics', url: 'https://www.youtube.com/watch?v=6-b_6kU5U4U' },
      { title: 'Khan Academy: Classical Genetics', url: 'https://www.khanacademy.org/science/biology/classical-genetics' },
    ],
    quiz: [
      { question: "Who is known as the father of genetics?", options: ['Darwin', 'Mendel', 'Morgan', 'Watson'], correct: 'Mendel' },
      { question: 'What is the phenotypic ratio of a dihybrid cross?', options: ['1:2:1', '3:1', '9:3:3:1', '1:1:1:1'], correct: '9:3:3:1' },
    ],
  },
  {
    id: 5,
    title: 'Molecular Basis of Inheritance',
    summary: 'A deep dive into the structure of DNA and the processes of replication, transcription, and translation that form the central dogma of molecular biology.',
    detailedExplanation: "This chapter explores the very blueprint of life. It begins with the search for the genetic material, culminating in the discovery of DNA's structure. The elegant process of DNA replication is detailed, followed by the central dogma: transcription (the synthesis of RNA from a DNA template) and translation (the synthesis of a protein from an mRNA template). The chapter deciphers the genetic code, explains the regulation of gene expression through models like the lac operon, and concludes with the monumental Human Genome Project and the powerful application of DNA fingerprinting.",
    keyTopics: ['The DNA', 'Search for Genetic Material', 'Replication', 'Transcription', 'Genetic Code', 'Translation', 'Regulation of Gene Expression', 'Human Genome Project', 'DNA Fingerprinting'],
    realWorldExample: 'DNA fingerprinting is used in forensic science to identify individuals and solve crimes.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Molecular Basis of Inheritance', url: 'https://www.khanacademy.org/science/biology/dna-as-the-genetic-material' },
      { title: 'PhET Simulation: Gene Expression', url: 'https://phet.colorado.edu/en/simulations/gene-expression-essentials' },
    ],
    quiz: [
      { question: 'What is the process of synthesizing RNA from a DNA template called?', options: ['Replication', 'Transcription', 'Translation', 'Reverse transcription'], correct: 'Transcription' },
      { question: 'Who proposed the double helix model of DNA?', options: ['Watson and Crick', 'Franklin and Wilkins', 'Hershey and Chase', 'Meselson and Stahl'], correct: 'Watson and Crick' },
    ],
  },
  {
    id: 6,
    title: 'Evolution',
    summary: 'An exploration of the origin of life and the mechanisms, such as natural selection and genetic drift, that drive evolutionary change over time.',
    detailedExplanation: "This unit traces the history of life on Earth, from theories on the origin of life to the grand narrative of biological evolution. It presents the evidence for evolution drawn from paleontology, comparative anatomy (homologous and analogous structures), and biochemistry. The core mechanisms of evolution, including natural selection, mutation, and genetic drift, are explained. The Hardy-Weinberg principle is introduced as a baseline to detect evolutionary change in a population. The chapter concludes with a brief account of geological time scales and the major events in human evolution.",
    keyTopics: ['Origin of Life', 'Evidence for Evolution', 'Mechanisms of Evolution', 'Hardy-Weinberg Principle', 'A Brief Account of Evolution', 'Origin and Evolution of Man'],
    realWorldExample: 'The evolution of antibiotic resistance in bacteria is a major public health concern.',
    keyEquation: "p^2 + 2pq + q^2 = 1",
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Crash Course Biology: Evolution', url: 'https://www.youtube.com/watch?v=P3GagfbA2vo' },
      { title: 'Khan Academy: Evolution and the Tree of Life', url: 'https://www.khanacademy.org/science/biology/her/evolution-and-natural-selection/v/introduction-to-evolution-and-natural-selection' },
    ],
    quiz: [
      { question: 'Who proposed the theory of evolution by natural selection?', options: ['Lamarck', 'Darwin', 'Mendel', 'Wallace'], correct: 'Darwin' },
      { question: 'What does the Hardy-Weinberg principle describe?', options: ['A population in evolutionary equilibrium', 'The process of natural selection', 'The rate of mutation', 'The process of speciation'], correct: 'A population in evolutionary equilibrium' },
    ],
  },
  {
    id: 7,
    title: 'Human Health and Disease',
    summary: 'An overview of common human diseases, the workings of the immune system, and major public health issues like cancer and drug abuse.',
    detailedExplanation: "This chapter provides a crucial understanding of human health. It discusses common infectious diseases caused by pathogens like bacteria, viruses, and protozoa (e.g., typhoid, pneumonia, malaria). A significant portion is dedicated to the immune system, distinguishing between innate and acquired immunity, and explaining the roles of B and T lymphocytes. The chapter also addresses major non-communicable diseases and health issues like cancer, AIDS, and the societal and physiological impacts of drug and alcohol abuse.",
    keyTopics: ['Common Diseases in Humans', 'Immunity (Innate and Acquired)', 'AIDS', 'Cancer', 'Drugs and Alcohol Abuse'],
    realWorldExample: 'Vaccination programs have successfully eradicated or controlled many infectious diseases like smallpox and polio.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Human Health and Disease', url: 'https://www.khanacademy.org/science/biology/human-biology/immunology/v/types-of-immunity' },
      { title: 'Amoeba Sisters: The Immune System', url: 'https://www.youtube.com/watch?v=fSEFXI2XQpc' },
    ],
    quiz: [
      { question: 'What is immunity?', options: ['The ability of the body to fight off disease', 'A type of disease', 'A type of drug', 'A type of vaccine'], correct: 'The ability of the body to fight off disease' },
      { question: 'What is cancer?', options: ['Uncontrolled cell growth', 'A bacterial infection', 'A viral infection', 'An autoimmune disease'], correct: 'Uncontrolled cell growth' },
    ],
  },
  {
    id: 8,
    title: 'Strategies for Enhancement in Food Production',
    summary: 'A look at the biological principles behind modern agriculture and animal husbandry aimed at increasing the global food supply.',
    detailedExplanation: "To meet the demands of a growing global population, this chapter explores strategies to enhance food production. It covers principles of animal husbandry, including breeding techniques (inbreeding and out-crossing) and the management of farms. The chapter then discusses plant breeding for developing high-yield and disease-resistant crop varieties, which was the cornerstone of the Green Revolution. Modern techniques like tissue culture for rapid plant propagation and the concept of Single Cell Protein (SCP) as an alternative food source are also introduced.",
    keyTopics: ['Animal Husbandry', 'Plant Breeding', 'Single Cell Protein', 'Tissue Culture'],
    realWorldExample: 'The Green Revolution led to a significant increase in food production through the development of high-yield crop varieties.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'BYJU\'S: Strategies for Enhancement in Food Production', url: 'https://byjus.com/biology/strategies-for-enhancement-in-food-production/' },
      { title: 'Toppr: Animal Husbandry', url: 'https://www.toppr.com/guides/biology/strategies-for-enhancement-in-food-production/animal-husbandry/' },
    ],
    quiz: [
      { question: 'What is the practice of breeding and raising livestock called?', options: ['Animal husbandry', 'Plant breeding', 'Apiculture', 'Pisciculture'], correct: 'Animal husbandry' },
      { question: 'What is tissue culture?', options: ['Growing plant cells, tissues, or organs in a sterile nutrient medium', 'Growing animal cells in a laboratory', 'Growing microorganisms in a fermenter', 'Cloning of animals'], correct: 'Growing plant cells, tissues, or organs in a sterile nutrient medium' },
    ],
  },
  {
    id: 9,
    title: 'Microbes in Human Welfare',
    summary: 'Exploring the surprisingly beneficial roles of microorganisms in household products, industrial processes, and environmental management.',
    detailedExplanation: "While often associated with disease, microbes play indispensable roles in our lives. This chapter highlights their positive contributions. We see their use in creating household products like curd and bread, and in the industrial production of beverages, antibiotics, and organic acids through fermentation. The chapter also explains the crucial role of microbes in sewage treatment plants to reduce pollution, in biogas production as a source of energy, and as biocontrol agents and biofertilizers in agriculture, offering an eco-friendly alternative to chemical pesticides and fertilizers.",
    keyTopics: ['Microbes in Household Products', 'Microbes in Industrial Products', 'Microbes in Sewage Treatment', 'Microbes in Biogas Production', 'Microbes as Biocontrol Agents', 'Microbes as Biofertilisers'],
    realWorldExample: 'Yeast is used in baking and brewing, while bacteria are used to make yogurt and cheese.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Fungi in the environment and industry', url: 'https://www.khanacademy.org/science/biology/fungi/fungal-classification-and-ecology/a/fungi-in-the-environment-and-industry' },
      { title: 'Vedantu: Microbes in Human Welfare', url: 'https://www.vedantu.com/biology/microbes-in-human-welfare' },
    ],
    quiz: [
      { question: 'Which microbe is used to make bread?', options: ['Lactobacillus', 'Saccharomyces cerevisiae', 'Aspergillus niger', 'Acetobacter aceti'], correct: 'Saccharomyces cerevisiae' },
      { question: "What is the primary gas produced in a biogas plant?", options: ['Methane', 'Carbon dioxide', 'Hydrogen sulfide', 'Oxygen'], correct: 'Methane' },
    ],
  },
  {
    id: 10,
    title: 'Biotechnology: Principles and Processes',
    summary: 'An introduction to the core tools of genetic engineering, such as restriction enzymes, vectors, and PCR, that allow for the manipulation of DNA.',
    detailedExplanation: "This chapter introduces the revolutionary field of biotechnology and its core principles. It focuses on recombinant DNA technology, the process of combining DNA from different sources. The key 'tools of the trade' are explained in detail: restriction enzymes ('molecular scissors') to cut DNA, ligases to join DNA fragments, cloning vectors (like plasmids) to carry foreign DNA into host cells, and the Polymerase Chain Reaction (PCR) to amplify DNA. The chapter outlines the complete process of creating a recombinant DNA molecule and using it to produce a desired product in a host organism.",
    keyTopics: ['Principles of Biotechnology', 'Tools of Recombinant DNA Technology', 'Restriction Enzymes', 'Cloning Vectors', 'Polymerase Chain Reaction (PCR)', 'Processes of R-DNA Technology'],
    realWorldExample: 'Insulin for diabetics is now produced using recombinant DNA technology.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Amoeba Sisters: Gel Electrophoresis', url: 'https://www.youtube.com/watch?v=OEUom4g5TTU' },
      { title: 'Khan Academy: Biotechnology', url: 'https://www.khanacademy.org/science/biology/biotech-dna-technology' },
    ],
    quiz: [
      { question: 'Which enzyme is used to cut DNA at specific sites?', options: ['Restriction enzyme', 'Ligase', 'Polymerase', 'Helicase'], correct: 'Restriction enzyme' },
      { question: "What does 'PCR' stand for?", options: ['Polymerase Chain Reaction', 'Protein Chain Reaction', 'Polynucleotide Chain Reaction', 'Phosphorus Chain Reaction'], correct: 'Polymerase Chain Reaction' },
    ],
  },
  {
    id: 11,
    title: 'Biotechnology and Its Applications',
    summary: 'Exploring the real-world impact of biotechnology in agriculture (GMOs), medicine (gene therapy), and the ethical issues that arise.',
    detailedExplanation: "Following the principles, this chapter showcases the applications of biotechnology. In agriculture, it discusses the creation of genetically modified organisms (GMOs) like Bt-cotton for pest resistance and 'Golden Rice' for enhanced nutritional value. In medicine, it covers the production of genetically engineered insulin, the development of vaccines, and the cutting-edge concept of gene therapy to correct genetic defects. The use of transgenic animals for research and the critical ethical issues surrounding genetic modification and biopiracy are also addressed.",
    keyTopics: ['Biotechnological Applications in Agriculture', 'Biotechnological Applications in Medicine', 'Gene Therapy', 'Transgenic Animals', 'Ethical Issues'],
    realWorldExample: 'Genetically modified crops like Bt cotton are resistant to pests.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'National Geographic: Genetically Modified Organisms (GMOs)', url: 'https://www.nationalgeographic.org/encyclopedia/genetically-modified-organisms/' },
      { title: 'Crash Course Biology: Biotechnology', url: 'https://www.youtube.com/watch?v=3IsQ9I4dBso' },
    ],
    quiz: [
      { question: 'What is a genetically modified organism (GMO)?', options: ['An organism whose genes have been altered using genetic engineering', 'An organism that has been cloned', 'An organism that has been hybridized', 'An organism that has been mutated'], correct: 'An organism whose genes have been altered using genetic engineering' },
      { question: 'What is gene therapy?', options: ['The correction of a genetic defect by inserting a normal gene', 'The use of genes to treat diseases', 'The diagnosis of genetic diseases', 'All of these'], correct: 'All of these' },
    ],
  },
  {
    id: 12,
    title: 'Organisms and Populations',
    summary: 'An introduction to ecology, focusing on how individual organisms adapt to their environment and how populations interact and grow.',
    detailedExplanation: "This is the first chapter in the ecology unit, focusing on the interactions between organisms and their environment. It discusses how organisms cope with abiotic factors like temperature and water through various adaptations. The second half shifts to the population level, defining attributes like birth rate, death rate, and age distribution. It explores models of population growth (exponential and logistic) and the concept of carrying capacity. Finally, it introduces different types of population interactions, such as predation, competition, parasitism, and mutualism.",
    keyTopics: ['Organism and Its Environment', 'Major Abiotic Factors', 'Adaptations', 'Populations and Attributes', 'Population Growth', 'Population Interactions'],
    realWorldExample: 'The predator-prey relationship between lions and zebras in the savanna is a classic example of population interaction.',
    keyEquation: 'dN/dt = rN((K-N)/K)',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Ecology Introduction', url: 'https://www.khanacademy.org/science/biology/ecology' },
      { title: 'National Geographic: Population Growth', url: 'https://www.nationalgeographic.org/encyclopedia/population-growth/' },
    ],
    quiz: [
      { question: 'What is a population?', options: ['A group of individuals of the same species in an area', 'A group of different species in an area', 'All organisms in an ecosystem', 'A community of organisms'], correct: 'A group of individuals of the same species in an area' },
      { question: 'What is mutualism?', options: ['An interaction where both species benefit', 'An interaction where one species benefits and the other is harmed', 'An interaction where one benefits and the other is unaffected', 'An interaction where both are harmed'], correct: 'An interaction where both species benefit' },
    ],
  },
  {
    id: 13,
    title: 'Ecosystem',
    summary: 'A study of the structure and function of ecosystems, including energy flow through food chains and the cycling of essential nutrients.',
    detailedExplanation: "This chapter examines the ecosystem as a functional unit of nature, where living organisms interact among themselves and with their physical environment. It details the components of an ecosystem: productivity (the rate of biomass production), decomposition (the breakdown of dead organic matter), and energy flow. The concept of trophic levels and food chains is used to explain the unidirectional flow of energy, often depicted using ecological pyramids. The chapter also covers ecological succession—the process of change in an ecosystem over time—and the biogeochemical cycles (like carbon and phosphorus) that recycle nutrients.",
    keyTopics: ['Ecosystem Structure and Function', 'Productivity', 'Decomposition', 'Energy Flow & Food Chains', 'Ecological Pyramids', 'Ecological Succession', 'Nutrient Cycling'],
    realWorldExample: 'Forests provide essential ecosystem services like clean air, water, and climate regulation.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Amoeba Sisters: Ecosystems', url: 'https://www.youtube.com/watch?v=v6ubvEJ3KGM' },
      { title: 'National Geographic: Ecosystems', url: 'https://www.nationalgeographic.org/encyclopedia/ecosystem/' },
    ],
    quiz: [
      { question: 'What is the primary source of energy for most ecosystems?', options: ['Sunlight', 'Chemical energy', 'Geothermal energy', 'Wind energy'], correct: 'Sunlight' },
      { question: 'Which ecological pyramid is always upright?', options: ['Pyramid of energy', 'Pyramid of numbers', 'Pyramid of biomass', 'All of these'], correct: 'Pyramid of energy' },
    ],
  },
  {
    id: 14,
    title: 'Biodiversity and Conservation',
    summary: 'An exploration of the vast variety of life on Earth, the threats it faces, and the strategies for its conservation.',
    detailedExplanation: "Biodiversity refers to the variety of life forms at all levels, from genes to species to entire ecosystems. This chapter discusses the patterns of biodiversity across the globe and its importance for ecosystem health and human well-being. It then highlights the major threats to biodiversity, collectively known as 'The Evil Quartet,' including habitat loss and fragmentation. Finally, it explores conservation strategies: in-situ conservation (protecting species in their natural habitats like national parks and hotspots) and ex-situ conservation (protecting them outside their habitats, in zoos and seed banks).",
    keyTopics: ['Biodiversity (Genetic, Species, Ecological)', 'Patterns of Biodiversity', 'Importance of Biodiversity', 'Loss of Biodiversity', 'Biodiversity Conservation (In-situ and Ex-situ)'],
    realWorldExample: 'National parks and wildlife sanctuaries are established to protect biodiversity.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'WWF: What is Biodiversity?', url: 'https://www.worldwildlife.org/pages/what-is-biodiversity' },
      { title: 'Crash Course Biology: Biodiversity', url: 'https://www.youtube.com/watch?v=iI-2w_nN2k' },
    ],
    quiz: [
      { question: 'Which of the following is a level of biodiversity?', options: ['Genetic diversity', 'Species diversity', 'Ecosystem diversity', 'All of these'], correct: 'All of these' },
      { question: 'Which of the following is an example of ex-situ conservation?', options: ['National park', 'Wildlife sanctuary', 'Biosphere reserve', 'Zoological park'], correct: 'Zoological park' },
    ],
  },
  {
    id: 15,
    title: 'Environmental Issues',
    summary: 'A discussion of major environmental problems caused by human activity, such as pollution, global warming, and deforestation, and their potential solutions.',
    detailedExplanation: "This concluding chapter addresses the pressing environmental challenges facing our planet. It covers air pollution and its control, including the problem of acid rain and smog. Water pollution and the effects of sewage and industrial effluents are also discussed, along with the management of solid and radioactive wastes. The chapter explains major global issues like the greenhouse effect and global warming, ozone layer depletion, and deforestation. It emphasizes the need for sustainable practices and legal frameworks to mitigate these environmental problems.",
    keyTopics: ['Air Pollution and Its Control', 'Water Pollution and Its Control', 'Solid Wastes', 'Greenhouse Effect and Global Warming', 'Ozone Depletion', 'Deforestation'],
    realWorldExample: 'The use of catalytic converters in automobiles helps to reduce air pollution.',
    keyEquation: '',
    icon: 'dna',
    visualizationLinks: [
      'https://www.visiblebody.com/learn/biology',
      'https://www.smart-biology.com/',
      'https://www.youtube.com/@bestforneet',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Environmental Science', url: 'https://www.khanacademy.org/science/environmental-science-and-engineering' },
      { title: 'NASA: Global Climate Change', url: 'https://climate.nasa.gov/' },
    ],
    quiz: [
      { question: 'What is the main cause of ozone depletion?', options: ['Chlorofluorocarbons (CFCs)', 'Carbon dioxide', 'Methane', 'Sulphur dioxide'], correct: 'Chlorofluorocarbons (CFCs)' },
      { question: "What is 'biomagnification'?", options: ['Increase in toxicant concentration at successive trophic levels', 'Decrease in toxicant concentration', 'Breakdown of toxicants', 'Accumulation of toxicants in an organism'], correct: 'Increase in toxicant concentration at successive trophic levels' },
    ],
  },
];

// =================================================================================
//                            PHYSICS CLASS 12
// =================================================================================
export const physicsXII = [
  {
    id: 1,
    title: 'Electric Charges and Fields',
    summary: "An introduction to electrostatics, exploring the nature of electric charge, the forces between charges, and the concept of the electric field.",
    detailedExplanation: "This chapter introduces the fundamental concept of electric charge and its properties, such as quantization and conservation. It establishes Coulomb's Law, which quantifies the force between two point charges. The concept of the electric field is developed as a region of influence around a charge, and electric field lines are used to visualize it. A significant part of the chapter is dedicated to Gauss's Law, a powerful tool that relates the electric flux through a closed surface to the net charge enclosed. This law is then applied to calculate the electric field for symmetrical charge distributions like infinite lines, sheets, and spheres.",
    keyTopics: ['Electric Charge', "Coulomb's Law", 'Electric Field & Field Lines', 'Electric Flux', "Gauss's Law & Applications"],
    realWorldExample: 'Photocopiers use static electricity (the principles of electric charges and fields) to attract toner particles to paper.',
    keyEquation: "F = k * |q1*q2| / r^2",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
        { title: 'Khan Academy: Electric Charge, Field, and Potential', url: 'https://www.khanacademy.org/science/physics/electric-charge-electric-force-and-voltage' },
        { title: 'PhET Simulation: Charges and Fields', url: 'https://phet.colorado.edu/en/simulations/charges-and-fields' },
    ],
    quiz: [
      { question: "What is the SI unit of electric charge?", options: ['Ampere', 'Coulomb', 'Volt', 'Ohm'], correct: 'Coulomb' },
      { question: "What does Coulomb's law describe?", options: ['The force between two charges', 'The electric field of a charge', 'The electric potential', 'The electric flux'], correct: 'The force between two charges' },
    ],
  },
  {
    id: 2,
    title: 'Electrostatic Potential and Capacitance',
    summary: 'A study of electric potential energy, potential difference, and the principles of capacitors as energy storage devices.',
    detailedExplanation: "Building on the concept of the electric field, this chapter introduces electric potential as the work done per unit charge to move a charge in an electric field. We explore potential due to point charges and dipoles, and the concept of equipotential surfaces. The chapter then moves to capacitance, defining it as the ability of a system to store electric charge. The parallel plate capacitor is analyzed in detail, including how its capacitance is affected by the geometry of the plates and the insertion of a dielectric material. Finally, we study how capacitors behave when combined in series and parallel circuits and calculate the energy stored within them.",
    keyTopics: ['Electrostatic Potential', 'Equipotential Surfaces', 'Potential Energy', 'Capacitors and Capacitance', 'Dielectrics and Polarisation', 'Energy Stored in a Capacitor'],
    realWorldExample: 'Capacitors are used in camera flashes to store and release electrical energy quickly.',
    keyEquation: "C = Q / V",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
        { title: 'The Organic Chemistry Tutor: Capacitors in Series and Parallel', url: 'https://www.youtube.com/watch?v=pDUSi42-t-I' },
        { title: 'PhET Simulation: Capacitor Lab', url: 'https://phet.colorado.edu/en/simulations/capacitor-lab-basics' },
    ],
    quiz: [
      { question: "What is a capacitor?", options: ['A device to store electrical energy', 'A device to measure current', 'A device to measure voltage', 'A resistor'], correct: 'A device to store electrical energy' },
      { question: "What happens to the capacitance when a dielectric is inserted between the plates?", options: ['It increases', 'It decreases', 'It remains the same', 'It becomes zero'], correct: 'It increases' },
    ],
  },
  {
    id: 3,
    title: 'Current Electricity',
    summary: 'An analysis of electric charges in motion, covering Ohm’s law, electrical resistance, and the principles of circuit analysis.',
    detailedExplanation: "This unit shifts from static charges to moving charges, or electric current. It begins with Ohm's Law, which defines the relationship between voltage, current, and resistance. The concepts of resistivity and its dependence on temperature are explored. The chapter then focuses on analyzing electrical circuits, introducing rules for combining resistors in series and parallel. Kirchhoff's Laws (Junction Rule and Loop Rule) are presented as fundamental principles for analyzing more complex circuits. Finally, practical instruments like the Wheatstone bridge, meter bridge, and potentiometer are discussed, showing how these principles are applied to measure unknown resistances and EMFs.",
    keyTopics: ['Electric Current', "Ohm's Law", 'Resistance and Resistivity', 'Combination of Resistors', 'Kirchhoff’s Laws', 'Measuring Instruments'],
    realWorldExample: 'Household wiring uses combinations of series and parallel circuits to distribute electricity.',
    keyEquation: "V = IR",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Crash Course Physics: Electric Current', url: 'https://www.youtube.com/watch?v=H9_62z84M0A' },
      { title: 'PhET Simulation: Circuit Construction Kit (DC)', url: 'https://phet.colorado.edu/en/simulations/circuit-construction-kit-dc' },
    ],
    quiz: [
      { question: "What is the SI unit of resistance?", options: ['Ohm', 'Ampere', 'Volt', 'Coulomb'], correct: 'Ohm' },
      { question: "What do Kirchhoff's laws describe?", options: ['Conservation of charge and energy in circuits', 'Behavior of magnetic fields', 'Properties of capacitors', 'Laws of thermodynamics'], correct: 'Conservation of charge and energy in circuits' },
    ],
  },
  {
    id: 4,
    title: 'Moving Charges and Magnetism',
    summary: 'An exploration of how moving charges create magnetic fields and experience forces within them, forming the basis of electromagnetism.',
    detailedExplanation: "This chapter establishes the connection between electricity and magnetism. It introduces the magnetic force experienced by a moving charge (the Lorentz force) and a current-carrying wire in a magnetic field. The Biot-Savart Law and Ampere's Circuital Law are presented as the primary tools for calculating the magnetic field produced by various current configurations, such as straight wires, loops, and solenoids. The principles behind the operation of devices like the cyclotron and the galvanometer are also explained, showcasing the practical applications of these forces.",
    keyTopics: ['Magnetic Force', 'Motion in a Magnetic Field', 'Biot-Savart Law', "Ampere's Circuital Law", 'Solenoid and Toroid', 'Force on Current-Carrying Conductors'],
    realWorldExample: 'Electric motors use the force on a current-carrying wire in a magnetic field to produce motion.',
    keyEquation: "F = q(v x B)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Magnetic forces, fields, and flux', url: 'https://www.khanacademy.org/science/physics/magnetic-forces-and-magnetic-fields' },
      { title: 'HyperPhysics: Magnetic Field', url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/magnetic/magfie.html' },
    ],
    quiz: [
      { question: "What is the SI unit of magnetic field?", options: ['Tesla', 'Gauss', 'Weber', 'Henry'], correct: 'Tesla' },
      { question: "What is the path of a charged particle moving perpendicular to a uniform magnetic field?", options: ['Circular', 'Helical', 'Parabolic', 'Straight line'], correct: 'Circular' },
    ],
  },
  {
    id: 5,
    title: 'Magnetism and Matter',
    summary: 'A study of the magnetic properties of materials, the behavior of bar magnets, and the Earth’s own magnetic field.',
    detailedExplanation: "This chapter delves into the behavior of magnetic materials and the concept of magnetism itself. It starts with the properties of a bar magnet, analogous to an electric dipole, and introduces Gauss's law for magnetism, which states that magnetic monopoles do not exist. The chapter then discusses the Earth's magnetic field and its elements. A key focus is the classification of materials based on their magnetic properties: diamagnetic, paramagnetic, and ferromagnetic. The behavior of these materials in an external magnetic field is explained using concepts like magnetization and magnetic susceptibility.",
    keyTopics: ['The Bar Magnet', "Gauss's Law for Magnetism", "The Earth's Magnetism", 'Magnetisation and Magnetic Intensity', 'Magnetic Properties of Materials', 'Permanent Magnets'],
    realWorldExample: 'A compass needle aligns with the Earth’s magnetic field to point north.',
    keyEquation: "B = μ₀(H + M)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'The Physics Classroom: Magnetism', url: 'https://www.physicsclassroom.com/class/magnets' },
      { title: 'BYJU\'S: Magnetism and Matter', url: 'https://byjus.com/physics/magnetism-and-matter/' },
    ],
    quiz: [
      { question: "What does Gauss's law for magnetism state?", options: ['Net magnetic flux through a closed surface is zero', 'Net magnetic flux through an open surface is zero', 'Net magnetic charge is zero', 'Net magnetic current is zero'], correct: 'Net magnetic flux through a closed surface is zero' },
      { question: "Which of the following is a ferromagnetic material?", options: ['Copper', 'Aluminum', 'Iron', 'Bismuth'], correct: 'Iron' },
    ],
  },
  {
    id: 6,
    title: 'Electromagnetic Induction',
    summary: 'Investigating how a changing magnetic field can induce an electric current, the principle behind generators and transformers.',
    detailedExplanation: "This chapter explores the phenomenon of electromagnetic induction (EMI), where a changing magnetic flux through a circuit induces an electromotive force (EMF) and hence a current. Faraday's Law of Induction quantifies this relationship, while Lenz's Law determines the direction of the induced current, reinforcing the principle of conservation of energy. The concepts of self-inductance and mutual inductance are introduced to describe the induction effects in single coils and between neighboring coils. The chapter culminates in the application of these principles to explain the working of AC generators and transformers.",
    keyTopics: ['Magnetic Flux', "Faraday's Law of Induction", "Lenz's Law", 'Motional EMF', 'Eddy Currents', 'Inductance (Self and Mutual)', 'AC Generator'],
    realWorldExample: 'Electric generators work on the principle of electromagnetic induction to produce electricity.',
    keyEquation: "ε = -dΦ/dt",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Electromagnetic induction and Faraday\'s law', url: 'https://www.khanacademy.org/science/physics/magnetic-forces-and-magnetic-fields/magnetic-flux-faradays-law/v/faradays-law-and-lenzs-law' },
      { title: 'PhET Simulation: Faraday\'s Law', url: 'https://phet.colorado.edu/en/simulations/faradays-law' },
    ],
    quiz: [
      { question: "What is electromagnetic induction?", options: ['Inducing an EMF with a changing magnetic field', 'Force on a moving charge', 'Magnetic field from a current', 'Force between currents'], correct: 'Inducing an EMF with a changing magnetic field' },
      { question: "What does Lenz's law state?", options: ["The induced current opposes the change that produced it", "The induced current is proportional to the magnetic flux", "The induced current is in the direction of the magnetic field", "The induced current is always clockwise"], correct: "The induced current opposes the change that produced it" },
    ],
  },
  {
    id: 7,
    title: 'Alternating Current',
    summary: 'An analysis of circuits with alternating current (AC), exploring the behavior of resistors, inductors, and capacitors and the concept of resonance.',
    detailedExplanation: "This chapter focuses on circuits where the current and voltage vary sinusoidally with time. It analyzes the behavior of individual components (resistors, inductors, and capacitors) in an AC circuit, introducing the concepts of reactance and impedance. The series LCR circuit is studied in detail, leading to the phenomenon of resonance, where the circuit allows maximum current at a specific frequency. The chapter also covers power in AC circuits, the power factor, and the principle of LC oscillations, which are fundamental to radio communication.",
    keyTopics: ['AC Voltage in R, L, and C circuits', 'Series LCR Circuit', 'Impedance and Reactance', 'Resonance', 'Power in AC Circuit', 'LC Oscillations', 'Transformers'],
    realWorldExample: 'The power grid supplies alternating current to homes and businesses.',
    keyEquation: "Z = sqrt(R^2 + (XL - XC)^2)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'The Physics Classroom: Alternating Current Circuits', url: 'https://www.physicsclassroom.com/class/circuits/Lesson-4/Alternating-Current' },
      { title: 'PhET Simulation: Circuit Construction Kit (AC)', url: 'https://phet.colorado.edu/en/simulations/circuit-construction-kit-ac' },
    ],
    quiz: [
      { question: "What is the phase relationship between voltage and current in a purely inductive AC circuit?", options: ['Voltage leads current by 90°', 'Current leads voltage by 90°', 'They are in phase', 'They are out of phase by 180°'], correct: 'Voltage leads current by 90°' },
      { question: "What is resonance in a series LCR circuit?", options: ['The condition where current is maximum', 'The condition where impedance is minimum', 'The condition where inductive reactance equals capacitive reactance', 'All of these'], correct: 'All of these' },
    ],
  },
  {
    id: 8,
    title: 'Electromagnetic Waves',
    summary: 'A study of the nature of electromagnetic waves, their properties, how they are produced, and the full spectrum of their forms.',
    detailedExplanation: "This chapter unifies electricity and magnetism by introducing electromagnetic (EM) waves. It explains Maxwell's prediction that accelerating charges produce oscillating electric and magnetic fields that propagate through space as a wave. The properties of EM waves, such as their transverse nature and their travel at the speed of light, are discussed. The chapter presents the full electromagnetic spectrum, arranging different types of waves (radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays) in order of wavelength and frequency, and highlights their diverse applications.",
    keyTopics: ['Displacement Current', 'Electromagnetic Waves', 'Nature of EM Waves', 'Electromagnetic Spectrum'],
    realWorldExample: 'Radio waves, microwaves, and X-rays are all forms of electromagnetic waves with different applications.',
    keyEquation: "c = 1 / sqrt(μ₀ε₀)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'NASA Science: Introduction to the Electromagnetic Spectrum', url: 'https://science.nasa.gov/ems/01_intro/' },
      { title: 'Khan Academy: Electromagnetic waves and the electromagnetic spectrum', url: 'https://www.khanacademy.org/science/physics/light-and-electromagnetic-waves/light-and-the-electromagnetic-spectrum/v/introduction-to-light' },
    ],
    quiz: [
      { question: "What is an electromagnetic wave?", options: ['A wave of oscillating electric and magnetic fields', 'A wave that requires a medium', 'A longitudinal wave', 'A wave that travels at the speed of sound'], correct: 'A wave of oscillating electric and magnetic fields' },
      { question: "Which of the following has the highest frequency?", options: ['Gamma rays', 'X-rays', 'Ultraviolet', 'Visible light'], correct: 'Gamma rays' },
    ],
  },
  {
    id: 9,
    title: 'Ray Optics and Optical Instruments',
    summary: 'A study of light propagation in terms of rays, covering reflection, refraction, and their application in optical instruments like microscopes and telescopes.',
    detailedExplanation: "This chapter treats light as rays traveling in straight lines. It begins with the laws of reflection and their application to spherical mirrors. It then moves to refraction, Snell's law, and the phenomenon of total internal reflection, which is the principle behind optical fibers. The lens maker's formula and the thin lens formula are derived and used to analyze image formation by lenses. The chapter also covers the dispersion of light through a prism and concludes by explaining the working principles of optical instruments like the simple microscope, compound microscope, and astronomical telescope.",
    keyTopics: ['Reflection by Spherical Mirrors', 'Refraction and Snell\'s Law', 'Total Internal Reflection', 'Lenses and Lens Maker\'s Formula', 'Refraction through a Prism', 'Optical Instruments'],
    realWorldExample: 'Eyeglasses and contact lenses use the principles of refraction to correct vision problems.',
    keyEquation: "1/f = (n-1)(1/R1 - 1/R2)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Geometric Optics', url: 'https://www.khanacademy.org/science/physics/geometric-optics' },
      { title: 'PhET Simulation: Geometric Optics', url: 'https://phet.colorado.edu/en/simulations/geometric-optics' },
    ],
    quiz: [
      { question: "What is total internal reflection?", options: ['Complete reflection of light at a boundary', 'Partial reflection of light', 'Absorption of light', 'Transmission of light'], correct: 'Complete reflection of light at a boundary' },
      { question: "What is the power of a lens?", options: ['The reciprocal of the focal length', 'The ability of a lens to bend light', 'Measured in diopters', 'All of these'], correct: 'All of these' },
    ],
  },
  {
    id: 10,
    title: 'Wave Optics',
    summary: 'An exploration of phenomena like interference, diffraction, and polarization that demonstrate the wave nature of light.',
    detailedExplanation: "This chapter shifts from the ray model to the wave model of light. It starts with Huygens' Principle to explain wave propagation. The core of the chapter is the study of interference, demonstrated by Young's double-slit experiment, which produces a characteristic pattern of bright and dark fringes. It then discusses diffraction, the bending of light around obstacles, which explains the patterns seen when light passes through a single slit. Finally, the chapter introduces polarization, a phenomenon unique to transverse waves, which deals with the orientation of the light wave's oscillations.",
    keyTopics: ["Huygens' Principle", 'Interference and Young’s Experiment', 'Diffraction', 'Polarisation'],
    realWorldExample: 'The colorful patterns seen on soap bubbles are due to interference of light waves.',
    keyEquation: "d sin(θ) = mλ",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'The Physics Classroom: Light Waves and Color', url: 'https://www.physicsclassroom.com/class/light' },
      { title: 'PhET Simulation: Wave Interference', url: 'https://phet.colorado.edu/en/simulations/wave-interference' },
    ],
    quiz: [
      { question: "What did Young's double-slit experiment demonstrate?", options: ['The wave nature of light through interference', 'The particle nature of light', 'The polarization of light', 'The photoelectric effect'], correct: 'The wave nature of light through interference' },
      { question: "Which of these phenomena demonstrates that light is a transverse wave?", options: ['Interference', 'Diffraction', 'Polarization', 'Reflection'], correct: 'Polarization' },
    ],
  },
  {
    id: 11,
    title: 'Dual Nature of Radiation and Matter',
    summary: 'A revolutionary concept that explores how light and matter can exhibit both wave-like and particle-like properties.',
    detailedExplanation: "This chapter marks the beginning of modern physics, challenging classical ideas. It explores the photoelectric effect, where light behaves as a stream of particles (photons) to eject electrons from a metal surface. This particle nature of light is a cornerstone of quantum theory. The chapter then introduces the radical de Broglie hypothesis, which proposes that matter (like electrons) also has a wave-like nature. This wave-particle duality is experimentally confirmed by the Davisson and Germer experiment, which showed electrons diffracting just like waves.",
    keyTopics: ['Photoelectric Effect', 'Einstein\'s Photoelectric Equation', 'Particle Nature of Light: The Photon', 'Wave Nature of Matter', 'de Broglie Relation', 'Davisson and Germer Experiment'],
    realWorldExample: 'Solar panels work on the principle of the photoelectric effect to convert sunlight into electricity.',
    keyEquation: "λ = h / p",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Quantum Physics', url: 'https://www.khanacademy.org/science/physics/quantum-physics' },
      { title: 'PhET Simulation: Photoelectric Effect', url: 'https://phet.colorado.edu/en/simulations/photoelectric' },
    ],
    quiz: [
      { question: "What is the photoelectric effect?", options: ['Emission of electrons from a material when light shines on it', 'Emission of photons from a material', 'Scattering of light by electrons', 'Interference of light waves'], correct: 'Emission of electrons from a material when light shines on it' },
      { question: "What did the Davisson and Germer experiment demonstrate?", options: ['The wave nature of electrons', 'The particle nature of electrons', 'The charge of an electron', 'The mass of an electron'], correct: 'The wave nature of electrons' },
    ],
  },
  {
    id: 12,
    title: 'Atoms',
    summary: 'A journey through the historical models of the atom, culminating in the Bohr model and its explanation of atomic spectra.',
    detailedExplanation: "This chapter traces the development of our understanding of atomic structure. It starts with early models and moves to Rutherford's nuclear model, which was based on the alpha-particle scattering experiment. While successful, Rutherford's model couldn't explain the stability of atoms or their discrete emission spectra. The chapter then focuses on the Bohr model of the hydrogen atom, which introduced the revolutionary concepts of quantized energy levels and electron orbits. This model successfully explains the line spectra of hydrogen, and de Broglie's hypothesis later provided a justification for Bohr's quantization postulate.",
    keyTopics: ['Rutherford’s Nuclear Model of Atom', 'Atomic Spectra', 'Bohr Model of the Hydrogen Atom', 'Line Spectra of the Hydrogen Atom', 'de Broglie’s Explanation of Bohr’s Postulate'],
    realWorldExample: 'Lasers work based on the principles of atomic energy levels and stimulated emission.',
    keyEquation: "1/λ = R (1/n1^2 - 1/n2^2)",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'PhET Simulation: Models of the Hydrogen Atom', url: 'https://phet.colorado.edu/en/simulations/models-of-the-hydrogen-atom' },
      { title: 'HyperPhysics: Bohr Model', url: 'http://hyperphysics.phy-astr.gsu.edu/hbase/bohrcn.html' },
    ],
    quiz: [
      { question: "What did Rutherford's alpha-particle scattering experiment show?", options: ['The atom has a small, dense, positive nucleus', 'Electrons orbit the nucleus like planets', 'The atom is a uniform positive sphere', 'Energy levels are quantized'], correct: 'The atom has a small, dense, positive nucleus' },
      { question: "What are the postulates of Bohr's model of the hydrogen atom?", options: ['Electrons are in fixed orbits', 'Angular momentum of electrons is quantized', 'Electrons radiate energy when they jump between levels', 'All of these'], correct: 'All of these' },
    ],
  },
  {
    id: 13,
    title: 'Nuclei',
    summary: 'An exploration into the heart of the atom, studying the composition of the nucleus, radioactivity, and the immense energy released in nuclear reactions.',
    detailedExplanation: "This chapter focuses on the atomic nucleus. It discusses the composition of the nucleus (protons and neutrons), its size, and the concept of isotopes. The idea of mass-energy equivalence (E=mc²) and nuclear binding energy is introduced to explain the stability of nuclei and the energy released in nuclear reactions. The chapter covers the phenomenon of radioactivity (alpha, beta, and gamma decay) and the law of radioactive decay. Finally, it explores the processes of nuclear fission and nuclear fusion, which are the basis for nuclear power and the energy source of stars.",
    keyTopics: ['Composition and Size of Nucleus', 'Mass-Energy and Nuclear Binding Energy', 'Nuclear Force', 'Radioactivity', 'Nuclear Fission and Fusion'],
    realWorldExample: 'Nuclear power plants use nuclear fission to generate electricity.',
    keyEquation: "E = mc^2",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'Khan Academy: Nuclear chemistry', url: 'https://www.khanacademy.org/science/chemistry/nuclear-chemistry' },
      { title: 'PhET Simulation: Nuclear Fission', url: 'https://phet.colorado.edu/en/simulations/nuclear-fission' },
    ],
    quiz: [
      { question: "What are isotopes?", options: ['Atoms with the same number of protons but different neutrons', 'Atoms with the same number of neutrons but different protons', 'Atoms with the same mass number', 'Atoms with the same number of electrons'], correct: 'Atoms with the same number of protons but different neutrons' },
      { question: "What is nuclear fission?", options: ['The splitting of a heavy nucleus', 'The fusion of two light nuclei', 'The emission of a neutron', 'The emission of a proton'], correct: 'The splitting of a heavy nucleus' },
    ],
  },
  {
    id: 14,
    title: 'Semiconductor Electronics',
    summary: 'An introduction to the materials, devices, and circuits that form the foundation of all modern electronics.',
    detailedExplanation: "This chapter explains the technology behind modern electronics. It begins by classifying materials as conductors, insulators, and semiconductors based on energy bands. It then focuses on semiconductors, explaining the difference between intrinsic (pure) and extrinsic (doped) types (n-type and p-type). The formation and behavior of the p-n junction, the fundamental building block of most semiconductor devices, is detailed. This leads to an understanding of the semiconductor diode as a rectifier. The chapter also covers the structure and working of transistors as amplifiers and switches, and concludes with an introduction to digital electronics and logic gates.",
    keyTopics: ['Conductors and Semiconductors', 'Intrinsic and Extrinsic Semiconductors', 'p-n Junction', 'Semiconductor Diode', 'Junction Transistor', 'Digital Electronics and Logic Gates'],
    realWorldExample: 'Computers, smartphones, and all modern electronics are based on semiconductor devices.',
    keyEquation: "Ie = Ib + Ic",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'The Organic Chemistry Tutor: Semiconductor Diodes', url: 'https://www.youtube.com/watch?v=gmjyAmo2w7M' },
      { title: 'All About Circuits: Logic Gates', url: 'https://www.allaboutcircuits.com/textbook/digital/chpt-3/logic-gates/' },
    ],
    quiz: [
      { question: "What is an intrinsic semiconductor?", options: ['A pure semiconductor', 'A doped semiconductor', 'A p-type semiconductor', 'An n-type semiconductor'], correct: 'A pure semiconductor' },
      { question: "What are the three terminals of a bipolar junction transistor (BJT)?", options: ['Emitter, base, and collector', 'Source, drain, and gate', 'Anode, cathode, and gate', 'Input, output, and ground'], correct: 'Emitter, base, and collector' },
    ],
  },
  {
    id: 15,
    title: 'Communication Systems',
    summary: 'A study of the principles behind transmitting information over long distances, including modulation, demodulation, and wave propagation.',
    detailedExplanation: "This chapter provides an overview of how information is transmitted from one place to another. It breaks down a communication system into its three essential elements: a transmitter, a channel, and a receiver. It discusses the need for modulation—superimposing a low-frequency information signal onto a high-frequency carrier wave—to enable efficient transmission. Different types of modulation, like Amplitude Modulation (AM), are explained. The chapter also covers the various ways electromagnetic waves propagate through the atmosphere (ground wave, sky wave, and space wave) to facilitate long-distance communication.",
    keyTopics: ['Elements of a Communication System', 'Bandwidth', 'Propagation of EM Waves', 'Modulation and its Necessity', 'Amplitude Modulation (AM)'],
    realWorldExample: 'Radio and television broadcasting, mobile phones, and the internet are all examples of communication systems.',
    keyEquation: "",
    icon: 'atom',
    visualizationLinks: [
      'https://phet.colorado.edu/',
      'https://ophysics.com/',
      'https://www.falstad.com/mathphysics.html',
    ],
    resourceLinks: [
      { title: 'TutorialsPoint: Communication Systems', url: 'https://www.tutorialspoint.com/communication_systems/index.htm' },
      { title: 'Physics LibreTexts: Modulation', url: 'https://phys.libretexts.org/Bookshelves/University_Physics/Book%3A_University_Physics_(OpenStax)/Map%3A_University_Physics_III_-_Optics_and_Modern_Physics_(OpenStax)/16%3A_Modern_Technology/16.03%3A_Modulation' },
    ],
    quiz: [
      { question: "What are the basic elements of a communication system?", options: ['Transmitter, channel, and receiver', 'Source, encoder, and decoder', 'Modulator, demodulator, and amplifier', 'Antenna, cable, and satellite'], correct: 'Transmitter, channel, and receiver' },
      { question: "Why is modulation necessary?", options: ['To transmit low-frequency signals over long distances', 'To avoid mixing of signals', 'To reduce the size of the antenna', 'All of these'], correct: 'All of these' },
    ],
  },
];


// =================================================================================
//                            FINAL EXPORT OBJECT
// =================================================================================
export const modulesData = {
  chemistryXII,
  biologyXII,
  physicsXII,
};